# Generated by Django 5.1.6 on 2025-02-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rename_cliente_pedido_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock actual disponible'),
        ),
    ]
