# Generated by Django 5.1.6 on 2025-02-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_pedidoproducto_costo_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_PRODUCCION', 'En Producción'), ('TERMINADO', 'Terminado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='NUEVO', max_length=20),
        ),
        migrations.CreateModel(
            name='PagoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banco', models.CharField(max_length=100)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion.pedido')),
            ],
        ),
    ]
